### ISSUE TITLE
clarify if keying of top level site should be eTLD+1 based

### ISSUE THREAD

**Issue by sohomdatta1** [kyraseevers/Partitioning-visited-links-history#2]
Based on reading https://github.com/kyraseevers/Partitioning-visited-links-history/blob/e084b3ebfc6c5183decba8aaf71c9331e11d9b6e/README.md?plain=1#L48-L56 it seems a bit unclear what a "site" means in this context. Based on the infographic, it seems to be based on the [eTLD+1](https://developer.mozilla.org/en-US/docs/Glossary/eTLD), but even using just keying by top level origin could potentially work here.

**Comment by kyraseevers** [comment]
Thanks for your question! Site here will be implemented as ["schemeful site"](https://github.com/sbingler/schemeful-same-site), which is eTLD+1 and scheme.

We did have some discussion of just keying by top-level origin. However, by keying by both frame origin and top-level site, it allows us to prevent sites embedded in iframes from determining the history of their embedders.
